services:
  sftp:
    image: atmoz/sftp
    container_name: t4-sftp
    ports:
      - "2222:22"
    volumes:
      - ./data/ftp/alumnos:/data
    command: >
      alumno1:Alumno123:1000:1000:/data/alumno1
      alumno2:Alumno123:1001:1001:/data/alumno2
      profesor:Profe123:1002:1002:/data/profesor
    restart: unless-stopped
